### ISSUE TITLE
Add the @hidden feature.

### ISSUE THREAD

**Issue by DongHY1** [JSerZANP/shaku#2]
Similar to the code example in this [blog post](https://pomb.us/build-your-own-react/), we can achieve this effect by adjusting the opacity.

<img width="521" alt="image" src="https://github.com/JSerZANP/shaku/assets/73568310/0cb13ede-dadf-4657-8921-6f6b5abc1dee">

Referring to the `@highlight` syntax, I have implemented the `@hidden` syntax to achieve this effect.

<img width="1232" alt="image" src="https://github.com/JSerZANP/shaku/assets/73568310/c034cda9-1617-44cb-8795-94f712f643e6">

**Comment by JSerZANP** [comment]
+1 for this idea, and thanks for your contribution. 
will leave comments on PR
