### ISSUE TITLE
Not support highlight in jsx

### ISSUE THREAD

**Issue by kingller** [JSerZANP/shaku#20]
**Describe the bug**
Not work when use with react, the code is as bellow,

```
class Code extends React.PureComponent {
    render(): React.ReactNode {
        return (
            <div className="buttons">
                {/* @highlight start */}
                <Button type="primary">主要</Button>
                <Button>次要</Button>
                <Button type="danger">危险</Button>
                <Button type="important">重要</Button>
                {/* @highlight end */}
            </div>
        );
    }
}
```

or 

```
class Code extends React.PureComponent {
    render(): React.ReactNode {
        return (
            <div className="buttons">
                // @highlight start
                <Button type="primary">主要</Button>
                <Button>次要</Button>
                <Button type="danger">危险</Button>
                <Button type="important">重要</Button>
                // @highlight end
            </div>
        );
    }
}
```

but it works well as bellow,
```
class Code extends React.PureComponent {
    render(): React.ReactNode {
        return (
            // @highlight start
            <div className="buttons">
                <Button type="primary">主要</Button>
                <Button>次要</Button>
                <Button type="danger">危险</Button>
                <Button type="important">重要</Button>
            </div>
            // @highlight end
        );
    }
}
```

**To Reproduce**
[shaku playground](https://shaku-web.vercel.app?code=%0A%0A**shaku-code-annotate**%20allows%20you%20to%20annotate%20the%20code%20snippets%2C%0Ain%20a%20different%20context.%0A%0A**Here%20is%20a%20callout**%0A%0A%60%60%60js%20annotate%0Aclass%20Code%20extends%20React.PureComponent%20%7B%0A%20%20%20%20render()%3A%20React.ReactNode%20%7B%0A%20%20%20%20%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20className%3D%22buttons%22%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%2F*%20%40highlight%20start%20*%2F%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CButton%20type%3D%22primary%22%3E%E4%B8%BB%E8%A6%81%3C%2FButton%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CButton%3E%E6%AC%A1%E8%A6%81%3C%2FButton%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CButton%20type%3D%22danger%22%3E%E5%8D%B1%E9%99%A9%3C%2FButton%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CButton%20type%3D%22important%22%3E%E9%87%8D%E8%A6%81%3C%2FButton%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%2F*%20%40highlight%20end%20*%2F%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20)%3B%0A%20%20%20%20%7D%0A%7D%0A%60%60%60%0A) 

**Expected behavior**
works well like this
![image](https://github.com/JSerZANP/shaku/assets/9544236/2f7ece37-1bb3-4d40-9cb4-67bd3169e860)

**Screenshots**

![image](https://github.com/JSerZANP/shaku/assets/9544236/d8323ec4-86e2-47d1-acef-ab574385855f)

**Comment by JSerZANP** [comment]
Thanks for the report. 
It is tricky because it is no longer a line-level comment, but inline.

I'll investigate more and try to fix it. Obviously we all love jsx

**Comment by JSerZANP** [comment]
This is fixed [shaku playground](https://shaku-web.vercel.app/?code=%0A%0A**shaku-code-annotate**%20allows%20you%20to%20annotate%20the%20code%20snippets%2C%0Ain%20a%20different%20context.%0A%0A**Here%20is%20a%20callout**%0A%0A%60%60%60js%20annotate%0Aclass%20Code%20extends%20React.PureComponent%20%7B%0A%20%20%20%20render()%3A%20React.ReactNode%20%7B%0A%20%20%20%20%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20className%3D%22buttons%22%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%2F*%20%40highlight%20start%20*%2F%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CButton%20type%3D%22primary%22%3E%E4%B8%BB%E8%A6%81%3C%2FButton%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CButton%3E%E6%AC%A1%E8%A6%81%3C%2FButton%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CButton%20type%3D%22danger%22%3E%E5%8D%B1%E9%99%A9%3C%2FButton%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CButton%20type%3D%22important%22%3E%E9%87%8D%E8%A6%81%3C%2FButton%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%2F*%20%40highlight%20end%20*%2F%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20)%3B%0A%20%20%20%20%7D%0A%7D%0A%60%60%60%0A)
