### ISSUE TITLE
Tutorial on adding a novice to use

### ISSUE THREAD

**Issue by tasty007** [JSerZANP/shaku#21]
I hope you can join some beginner's tutorials in readme,

this can help a lot of people to use these plug-ins,

i'd love to, but I don't know how yet.

**Comment by JSerZANP** [comment]
Agreed. This is indeed is not begineer-friendly.

**Comment by JSerZANP** [comment]
Now we have a new homepage which addresses this issue https://shaku-web.vercel.app/
