### ISSUE TITLE
bug: dangling comment block 

### ISSUE THREAD

**Issue by JSerZANP** [JSerZANP/shaku#6]
<img width="935" alt="Screenshot 2023-05-20 at 22 07 09" src="https://github.com/JSerZANP/shaku/assets/69352453/cdd651db-bf0e-43bd-a944-4731bc2d7c2d">

for comment block `/* */` there is a dangling issue, especially for language like CSS/HTML

**Comment by Seven-Y-Q-Guo** [comment]
Hi @JSerZANP , I have an idea on resolving this issue:
Transform below codes
```
const blog = "https://jser.dev"
/*                    ^
       [JSer.dev is the *homepage* for JSer.]
       [Check it out! [jser.dev](https://jser.dev)]
*/
// This is a normal comment
```
into
```
const blog = "https://jser.dev"
//                    ^
//       [JSer.dev is the *homepage* for JSer.]
//       [Check it out! [jser.dev](https://jser.dev)]
// This is a normal comment
```

We can simply check the first content for each line, as I see another usage which looks like `{/*   [This is line 2]       */}` always has `{` as first content.
Once we have met `/*` we can add `//` between `/*` and `*/`.
My PR: https://github.com/JSerZANP/shaku/pull/61

**Comment by JSerZANP** [comment]
in the latest shaku transformer, this is no longer needed since we are going to be base on singe lines, no comment blocks https://github.com/JSerZANP/shaku/tree/main/packages/shaku-code-annotate-shiki-transformer
