### ISSUE TITLE
Using the user custom naming convention instead of js annotate.

### ISSUE THREAD

**Issue by DongHY1** [JSerZANP/shaku#9]
Using the identification `js annotate` for each code block seems boring,When writing technical articles, we often say something like: **"let's create a foo.js file."**
-  For example, we can giving a name to this code block, consider the following code snippet:

<img width="336" alt="image" src="https://github.com/JSerZANP/shaku/assets/73568310/718a44d8-46ac-4d76-8e8a-0e8148a66be0">

- We can also enhance its appearance through UI redesign to resemble the image below: 

<img width="367" alt="image" src="https://github.com/JSerZANP/shaku/assets/73568310/010f2973-3337-4adc-ba95-4f7f9f014ff0">

Is it necessary to add this feature?

**Comment by JSerZANP** [comment]
> Using the identification `js annotate` for each code block seems boring,

\`\`\`js is the syntax of markdown code block, for us only the `annotate` is the trigger.

> we can giving a name to this code block

Maybe this is the plugin you need https://github.com/kevinzunigacuellar/remark-code-title

> custom  naming convention

I don't think we should allow user change the trigger. 
It might be useful if we can add an option in the plugin saying that apply shaku to all code blocks ? but this again requires us to provide an option to opt out for specific code blocks, which seems not quite worth of it.

**Comment by DongHY1** [comment]
> > Using the identification `js annotate` for each code block seems boring,
> 
> ```js is the syntax of markdown code block, for us only the `annotate` is the trigger.
> 
> > we can giving a name to this code block
> 
> Maybe this is the plugin you need https://github.com/kevinzunigacuellar/remark-code-title
> 
> > custom  naming convention
> 
> I don't think we should allow user to change the trigger. It might be useful if we can add an option in the plugin saying that apply shaku to all code blocks ? but this again requires us to provide an option to opt out for specific code blocks, which seems not quite worth of it.

nice plugin!

**Comment by JSerZANP** [comment]
I'll close it for now
